// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQosHeoPphZDFbvV7LTqOB3PpRQFtHIns',
    appId: '1:802064574489:web:04993dc5e9e716d92de288',
    messagingSenderId: '802064574489',
    projectId: 'library-anime-88d29',
    authDomain: 'library-anime-88d29.firebaseapp.com',
    storageBucket: 'library-anime-88d29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQRChthPrivWSg8WeguqxqGX1GoU0QGw',
    appId: '1:802064574489:android:5fc8750e22ed01e42de288',
    messagingSenderId: '802064574489',
    projectId: 'library-anime-88d29',
    storageBucket: 'library-anime-88d29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw5_LMPj6xAd6GaE3dxIeih3rHdA1-dPY',
    appId: '1:802064574489:ios:cf06da58045aa5e52de288',
    messagingSenderId: '802064574489',
    projectId: 'library-anime-88d29',
    storageBucket: 'library-anime-88d29.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw5_LMPj6xAd6GaE3dxIeih3rHdA1-dPY',
    appId: '1:802064574489:ios:cf06da58045aa5e52de288',
    messagingSenderId: '802064574489',
    projectId: 'library-anime-88d29',
    storageBucket: 'library-anime-88d29.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQosHeoPphZDFbvV7LTqOB3PpRQFtHIns',
    appId: '1:802064574489:web:2afd0449797884812de288',
    messagingSenderId: '802064574489',
    projectId: 'library-anime-88d29',
    authDomain: 'library-anime-88d29.firebaseapp.com',
    storageBucket: 'library-anime-88d29.firebasestorage.app',
  );
}
